/**
 * Main barrel export for all services
 * Usage: import { tauriCommands, localStorage, terminalCommands, etc. } from '$lib/services';
 */

// Infrastructure Services
export {
	tauriCommands,
	tauriEvents,
	tauriDialog,
	tauriFs,
	terminalCommands,
	terminalEvents,
	localStorage,
	fileStorage,
	networkStateMonitor,
	networkOnline,
	detectAvailableShells,
	getCurrentPlatform
} from './infra/index.js';

// Data Services
export {
	setWorkspacesStore,
	getWorkspaceDataPath,
	getWorkspaceAvatarPath,
	loadWorkspaces,
	saveWorkspaces,
	addWorkspace,
	updateWorkspace,
	deleteWorkspace,
	getWorkspaces,
	getWorkspaceById,
	getCurrentWorkspaceId,
	setCurrentWorkspace,
	isWorkspaceNameDuplicate,
	createWorkspaceDirectory,
	deleteWorkspaceDirectory,
	saveWorkspaceAvatar,
	deleteWorkspaceAvatar,
	isFirstLaunch,
	createDefaultWorkspace,
	switchWorkspace,
	getWorkspaceInitials,
	keychainStore,
	loadKeychain,
	saveKeychain,
	addKey,
	updateKey,
	deleteKey,
	exportKey,
	getKeys,
	getKeysByVault,
	getVaults,
	isLabelDuplicate,
	isKeyDuplicate,
	findDuplicateKey,
	importKeyFromFile,
	hostsStore,
	loadHosts,
	saveHosts,
	addHost,
	updateHost,
	deleteHost,
	duplicateHost,
	getHosts,
	getHostsByGroup,
	getHostById,
	isHostLabelDuplicate,
	getGroups,
	addGroup,
	updateGroup,
	deleteGroup,
	getGroupById,
	isGroupNameDuplicate,
	getHostTags,
	snippetsStore,
	loadSnippets,
	saveSnippets,
	addSnippet,
	updateSnippet,
	deleteSnippet,
	duplicateSnippet,
	getSnippets,
	getSnippetById,
	isSnippetNameDuplicate,
	getSnippetTags,
	incrementSnippetClickCount,
	appSettingsStore,
	loadSettings,
	saveSettings,
	getAutoReconnectSettings,
	getHeartbeatSettings,
	updateAutoReconnectSettings,
	getUiSettings,
	updateUiSettings,
	getShortcuts,
	getShellPreferences,
	updateShortcuts,
	updateShellPreferences,
	getDefaultShell
} from './data/index.js';

// Connection Services
export {
	connectionFactory,
	BaseConnectionHandler,
	SSHConnectionHandler,
	FileTransferConnectionHandler,
	TelnetConnectionHandler,
	connectSSH,
	retrySSHConnection,
	writeTempKeyFile,
	prepareHopConfig,
	resolveChain,
	cleanupTempKeys,
	connectTelnet,
	retryTelnetConnection,
	connectFileTransfer,
	isFileTransferType,
	isTerminalType,
	connectionHeartbeat,
	attemptReconnect,
	cancelReconnect,
	isReconnecting
} from './connection/index.js';

// Sync Services
export {
	loadSyncSettings,
	saveSyncSettings,
	clearSyncSettings,
	validateGitHubCredentials,
	downloadFromGitHub,
	getGistHistory,
	downloadGistVersion,
	uploadToGitHub,
	buildEncryptedParts,
	initAutoSync,
	stopAutoSync,
	triggerManualSync,
	markLoadingStart,
	markLoadingComplete,
	exportSyncData,
	generateExportFilename,
	importSyncData,
	syncCheckerFactory,
	performCheckForUpdates,
	performGetLatestVersion,
	performUpload,
	performDownload
} from './sync/index.js';

// Utility Services
export {
	createTempFilePath,
	registerTempFile,
	unregisterTempFile,
	cleanupTempFile,
	cleanupAllTempFiles,
	getActiveTempFiles,
	getTempFileInfo,
	startWatching,
	stopWatching,
	checkMigrationNeeded,
	migrateExistingUser,
	restoreFromBackup,
	createLocalTerminal,
	keyboardShortcutManager,
	parseSSHConfig
} from './utils/index.js';

// File Services
export {
	createFileService,
	listLocalFiles,
	listRemoteFiles,
	downloadFile,
	uploadFile,
	deleteLocalFile,
	deleteRemoteFile,
	createLocalDirectory,
	createRemoteDirectory,
	renameLocalFile,
	renameRemoteFile,
	getLocalFileStat,
	getRemoteFileStat,
	closeFileSession,
	getParentPath,
	isWindowsPath,
	getHomeDirectory,
	joinPath,
	showInFileManager,
	openFileWithSystem,
	openFileWithApp,
	showOpenWithDialog,
	formatFileSize,
	getFileExtension,
	isAbsolutePath,
	chmodRemote,
	readFileContent,
	writeFileContent,
	copyLocalPath,
	moveLocalPath,
	copyRemotePath,
	moveRemotePath,
	createFileSession,
	getAppPreference,
	setAppPreference,
	clearAppPreference,
	getAllAppPreferences,
	initFileTransferProgressListener
} from './files/index.js';
